require_relative 'user_type.rb'
require_relative 'blog_type.rb'
require_relative 'post_type.rb'
require_relative 'comment_type.rb'
require_relative 'reaction_type.rb'
require_relative 'query_type.rb'
